package dev.tuprel.codegen;

import dev.tuprel.schema.SourceSpan;
import dev.tuprel.schema.ast.SchemaDocument;
import dev.tuprel.schema.model.ValidatedSchema;
import dev.tuprel.schema.model.ValidatedSchema.ResolvedType;
import dev.tuprel.schema.model.ValidatedSchema.TypeKind;
import dev.tuprel.schema.model.ValidatedSchema.ValidatedEnum;
import dev.tuprel.schema.model.ValidatedSchema.ValidatedField;
import dev.tuprel.schema.model.ValidatedSchema.ValidatedModel;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

/** Renders a validated Tuprel schema into deterministic, JDK-only Java 21 sources. */
public final class JavaCodeGenerator {
    private static final String HEADER = "// Generated by Tuprel. Do not edit.\n";
    private static final Set<String> RESERVED_TYPES = Set.of(
            "BigDecimal", "Boolean", "Byte", "Character", "Class", "Double", "Float",
            "Instant", "Integer", "List", "LocalDate", "LocalDateTime", "LocalTime",
            "Long", "Object", "Objects", "Short", "String", "TuprelBytes", "TuprelField",
            "TuprelInput", "TuprelJson", "TuprelModel", "TuprelSchema", "UUID");
    private static final Set<String> RESERVED_MEMBERS = Set.of(
            "build", "builder", "clone", "equals", "finalize", "getClass", "hashCode",
            "notify", "notifyAll", "toString", "wait");

    /** Generates source in memory; no output tree is touched. */
    public JavaGenerationResult generate(ValidatedSchema schema) {
        Objects.requireNonNull(schema, "schema");
        List<GenerationDiagnostic> diagnostics = inspect(schema);
        if (!diagnostics.isEmpty()) {
            return new JavaGenerationResult(Optional.empty(), diagnostics);
        }
        String root = ((SchemaDocument.StringLiteral)
                schema.generator().orElseThrow().properties().get("package")).value();
        Map<String, String> files = new TreeMap<>();
        put(files, root, "TuprelInput", renderInputSupport(root));
        put(files, root, "TuprelField", renderFieldSupport(root));
        put(files, root, "TuprelModel", renderModelSupport(root));
        put(files, root, "TuprelBytes", renderBytes(root));
        put(files, root, "TuprelJson", renderJson(root));
        put(files, root, "TuprelSchema", renderSchema(root, schema.models()));
        for (ValidatedEnum declaration : schema.enums()) {
            put(files, root + ".model", declaration.name(), renderEnum(root, declaration));
        }
        for (ValidatedModel model : schema.models()) {
            put(files, root + ".model", model.name(), renderModel(root, model));
            put(files, root + ".create", model.name() + "Create", renderInput(root, model, false));
            put(files, root + ".update", model.name() + "Update", renderInput(root, model, true));
            put(files, root + ".fields", model.name() + "Fields", renderFields(root, model));
            put(files, root + ".where", model.name() + "Where", renderWhere(root, model));
        }
        return new JavaGenerationResult(Optional.of(new GeneratedJavaSources(files)), List.of());
    }

    private static List<GenerationDiagnostic> inspect(ValidatedSchema schema) {
        List<GenerationDiagnostic> diagnostics = new ArrayList<>();
        if (schema.generator().isEmpty()) {
            diagnostics.add(diagnostic("001", "Java generation requires generator java with package.",
                    schema.syntax().span()));
            return diagnostics;
        }
        var config = schema.generator().orElseThrow();
        if (!(config.properties().get("package") instanceof SchemaDocument.StringLiteral literal)
                || !literal.value().matches("[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*")) {
            diagnostics.add(diagnostic("002", "Generator package must be a valid Java package name.",
                    config.span()));
            return diagnostics;
        }
        String packageName = literal.value();
        if (packageName.equals("java") || packageName.startsWith("java.")) {
            diagnostics.add(diagnostic("009", "Generator package cannot use the reserved java namespace.",
                    config.span()));
        }
        int segmentStart = 0;
        for (int index = 0; index <= packageName.length(); index++) {
            if (index == packageName.length() || packageName.charAt(index) == '.') {
                String segment = packageName.substring(segmentStart, index);
                if (deviceName(segment)) {
                    diagnostics.add(diagnostic("008", "Generator package segment is a reserved filesystem name: "
                            + segment, config.span()));
                }
                segmentStart = index + 1;
            }
        }
        Set<String> typeNames = new HashSet<>();
        Set<String> derivedNames = new HashSet<>();
        for (ValidatedModel model : schema.models()) {
            for (String suffix : List.of("Create", "Update", "Fields", "Where")) {
                derivedNames.add((model.name() + suffix).toLowerCase(Locale.ROOT));
            }
        }
        for (ValidatedModel model : schema.models()) {
            inspectType(model.name(), model.span(), typeNames, diagnostics);
            if (derivedNames.contains(model.name().toLowerCase(Locale.ROOT))) {
                diagnostics.add(diagnostic("007", "Java type name conflicts with a generated companion: "
                        + model.name(), model.span()));
            }
            Set<String> fieldNames = new HashSet<>();
            Set<String> constantNames = new HashSet<>();
            for (ValidatedField field : model.fields()) {
                if (!fieldNames.add(field.name().toLowerCase(Locale.ROOT))
                        || !constantNames.add(field.name().toUpperCase(Locale.ROOT))) {
                    diagnostics.add(diagnostic("004", "Java field name collides after case folding: "
                            + field.name(), field.span()));
                }
                if (RESERVED_MEMBERS.contains(field.name())) {
                    diagnostics.add(diagnostic("005", "Java field name conflicts with a generated or inherited method: "
                            + field.name(), field.span()));
                }
                if (field.type().kind() == TypeKind.SCALAR && scalar(field.type(), false) == null) {
                    diagnostics.add(diagnostic("006", "Unsupported Java scalar: " + field.type().name(),
                            field.span()));
                }
            }
        }
        for (ValidatedEnum enumeration : schema.enums()) {
            inspectType(enumeration.name(), enumeration.span(), typeNames, diagnostics);
            if (derivedNames.contains(enumeration.name().toLowerCase(Locale.ROOT))) {
                diagnostics.add(diagnostic("007", "Java type name conflicts with a generated companion: "
                        + enumeration.name(), enumeration.span()));
            }
        }
        return diagnostics;
    }

    private static void inspectType(String name, SourceSpan span, Set<String> names,
            List<GenerationDiagnostic> diagnostics) {
        if (RESERVED_TYPES.contains(name) || deviceName(name)
                || !names.add(name.toLowerCase(Locale.ROOT))) {
            diagnostics.add(diagnostic("003", "Java type name conflicts with another generated or JDK type: "
                    + name, span));
        }
    }

    private static boolean deviceName(String name) {
        return name.toUpperCase(Locale.ROOT).matches("CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9]");
    }

    private static GenerationDiagnostic diagnostic(String suffix, String message, SourceSpan span) {
        return new GenerationDiagnostic("TUPREL-CODEGEN-" + suffix, message, span);
    }

    private static void put(Map<String, String> files, String packageName, String name, String content) {
        files.put(packageName.replace('.', '/') + "/" + name + ".java", content);
    }

    private static String source(String packageName, Set<String> imports, String body) {
        StringBuilder result = new StringBuilder(HEADER).append("package ").append(packageName)
                .append(";\n\n");
        for (String item : new TreeSet<>(imports)) {
            result.append("import ").append(item).append(";\n");
        }
        if (!imports.isEmpty()) {
            result.append('\n');
        }
        return result.append(body).toString();
    }

    private static String scalar(ResolvedType type, boolean boxed) {
        if (type.kind() != TypeKind.SCALAR) {
            return type.name();
        }
        return switch (type.name()) {
            case "String" -> "String";
            case "Boolean" -> boxed ? "Boolean" : "boolean";
            case "Short" -> boxed ? "Short" : "short";
            case "Int" -> boxed ? "Integer" : "int";
            case "Long" -> boxed ? "Long" : "long";
            case "Decimal" -> "BigDecimal";
            case "Float" -> boxed ? "Float" : "float";
            case "Double" -> boxed ? "Double" : "double";
            case "UUID" -> "UUID";
            case "Instant" -> "Instant";
            case "LocalDateTime" -> "LocalDateTime";
            case "LocalDate" -> "LocalDate";
            case "LocalTime" -> "LocalTime";
            case "Bytes" -> "TuprelBytes";
            case "Json" -> "TuprelJson";
            default -> null;
        };
    }

    private static String javaType(ValidatedField field, boolean boxed) {
        String element = scalar(field.type(), boxed || field.cardinality() != SchemaDocument.Cardinality.REQUIRED);
        return field.cardinality() == SchemaDocument.Cardinality.LIST
                ? "List<" + scalar(field.type(), true) + ">" : element;
    }

    private static void importsFor(Set<String> imports, ValidatedField field, String root) {
        if (field.cardinality() == SchemaDocument.Cardinality.LIST) {
            imports.add("java.util.List");
        }
        if (field.type().kind() == TypeKind.ENUM || field.type().kind() == TypeKind.MODEL) {
            imports.add(root + ".model." + field.type().name());
            return;
        }
        switch (field.type().name()) {
            case "Decimal" -> imports.add("java.math.BigDecimal");
            case "UUID" -> imports.add("java.util.UUID");
            case "Instant", "LocalDate", "LocalDateTime", "LocalTime" ->
                    imports.add("java.time." + field.type().name());
            case "Bytes", "Json" -> imports.add(root + ".Tuprel" + field.type().name());
            default -> { }
        }
    }

    private static String quote(String value) {
        StringBuilder quoted = new StringBuilder("\"");
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            switch (character) {
                case '\\' -> quoted.append("\\\\");
                case '"' -> quoted.append("\\\"");
                case '\n' -> quoted.append("\\n");
                case '\r' -> quoted.append("\\r");
                case '\t' -> quoted.append("\\t");
                default -> quoted.append(character);
            }
        }
        return quoted.append('"').toString();
    }

    private static String renderEnum(String root, ValidatedEnum enumeration) {
        return source(root + ".model", Set.of(), "public enum " + enumeration.name() + " {\n    "
                + String.join(",\n    ", enumeration.values()) + "\n}\n");
    }

    private static String renderModel(String root, ValidatedModel model) {
        Set<String> imports = new TreeSet<>();
        List<ValidatedField> fields = model.fields().stream()
                .filter(field -> field.type().kind() != TypeKind.MODEL).toList();
        for (ValidatedField field : fields) {
            importsFor(imports, field, root);
            imports.remove(root + ".model." + field.type().name());
            if (field.cardinality() != SchemaDocument.Cardinality.OPTIONAL
                    && !javaType(field, false).matches("boolean|short|int|long|float|double")) {
                imports.add("java.util.Objects");
            }
        }
        StringBuilder body = new StringBuilder("/** Immutable value for model ")
                .append(model.name()).append("; relations are represented by metadata only. */\n")
                .append("public record ").append(model.name()).append("(");
        for (int index = 0; index < fields.size(); index++) {
            ValidatedField field = fields.get(index);
            if (index > 0) {
                body.append(", ");
            }
            body.append(javaType(field, false)).append(' ').append(field.name());
        }
        body.append(") {\n");
        if (!fields.isEmpty()) {
            body.append("    public ").append(model.name()).append(" {\n");
            for (ValidatedField field : fields) {
                if (field.cardinality() == SchemaDocument.Cardinality.LIST) {
                    body.append("        ").append(field.name()).append(" = List.copyOf(")
                            .append(field.name()).append(");\n");
                } else if (field.cardinality() == SchemaDocument.Cardinality.REQUIRED
                        && !javaType(field, false).matches("boolean|short|int|long|float|double")) {
                    body.append("        Objects.requireNonNull(").append(field.name()).append(", ")
                            .append(quote(field.name())).append(");\n");
                }
            }
            body.append("    }\n");
        }
        return source(root + ".model", imports, body.append("}\n").toString());
    }

    private static String renderInput(String root, ValidatedModel model, boolean update) {
        String suffix = update ? "Update" : "Create";
        String name = model.name() + suffix;
        List<ValidatedField> fields = model.fields().stream()
                .filter(field -> field.type().kind() != TypeKind.MODEL && (!update || !field.id()))
                .toList();
        Set<String> imports = new TreeSet<>();
        imports.add(root + ".TuprelInput");
        for (ValidatedField field : fields) {
            importsFor(imports, field, root);
            if (field.cardinality() == SchemaDocument.Cardinality.REQUIRED) {
                imports.add("java.util.Objects");
            }
        }
        StringBuilder body = new StringBuilder("/** Immutable ").append(suffix.toLowerCase(Locale.ROOT))
                .append(" input for ").append(model.name()).append(". */\npublic final class ")
                .append(name).append(" {\n");
        for (ValidatedField field : fields) {
            body.append("    private final TuprelInput<").append(javaType(field, true)).append("> ")
                    .append(field.name()).append(";\n");
        }
        body.append("\n    private ").append(name).append("(Builder builder) {\n");
        for (ValidatedField field : fields) {
            body.append("        this.").append(field.name()).append(" = builder.")
                    .append(field.name()).append(";\n");
        }
        body.append("    }\n\n    public static Builder builder() {\n        return new Builder();\n    }\n");
        for (ValidatedField field : fields) {
            body.append("\n    public TuprelInput<").append(javaType(field, true)).append("> ")
                    .append(field.name()).append("() {\n        return ").append(field.name())
                    .append(";\n    }\n");
        }
        body.append("\n    public static final class Builder {\n");
        for (ValidatedField field : fields) {
            body.append("        private TuprelInput<").append(javaType(field, true)).append("> ")
                    .append(field.name()).append(" = TuprelInput.absent();\n");
        }
        body.append("\n        private Builder() {}\n");
        for (ValidatedField field : fields) {
            body.append("\n        public Builder ").append(field.name()).append('(')
                    .append(javaType(field, true)).append(" value) {\n            this.")
                    .append(field.name()).append(" = TuprelInput.of(");
            if (field.cardinality() == SchemaDocument.Cardinality.LIST) {
                body.append("List.copyOf(value)");
            } else if (field.cardinality() == SchemaDocument.Cardinality.REQUIRED) {
                body.append("Objects.requireNonNull(value, ").append(quote(field.name())).append(')');
            } else {
                body.append("value");
            }
            body.append(");\n            return this;\n        }\n");
        }
        body.append("\n        public ").append(name).append(" build() {\n");
        if (!update) {
            for (ValidatedField field : fields) {
                if (field.cardinality() == SchemaDocument.Cardinality.REQUIRED
                        && field.defaultValue().isEmpty()) {
                    body.append("            if (!").append(field.name()).append(".present()) {\n")
                            .append("                throw new IllegalStateException(")
                            .append(quote("Required create field missing: " + field.name()))
                            .append(");\n            }\n");
                }
            }
        }
        body.append("            return new ").append(name).append("(this);\n        }\n")
                .append("    }\n}\n");
        return source(root + (update ? ".update" : ".create"), imports, body.toString());
    }

    private static String renderFields(String root, ValidatedModel model) {
        Set<String> imports = new TreeSet<>();
        imports.add(root + ".TuprelField");
        StringBuilder body = new StringBuilder("/** Structural fields for ")
                .append(model.name()).append("; no query execution. */\npublic final class ")
                .append(model.name()).append("Fields {\n");
        for (ValidatedField field : model.fields()) {
            importsFor(imports, field, root);
            body.append("    public static final TuprelField<").append(javaType(field, true))
                    .append("> ").append(field.name().toUpperCase(Locale.ROOT))
                    .append(" = new TuprelField<>(").append(quote(field.name())).append(", ")
                    .append(quote(field.type().name())).append(", TuprelField.Cardinality.")
                    .append(field.cardinality().name()).append(", ")
                    .append(field.type().kind() == TypeKind.MODEL
                            ? quote(field.type().name()) : "null")
                    .append(");\n");
        }
        body.append("\n    private ").append(model.name()).append("Fields() {}\n}\n");
        return source(root + ".fields", imports, body.toString());
    }

    private static String renderWhere(String root, ValidatedModel model) {
        Set<String> imports = new TreeSet<>();
        imports.add(root + ".TuprelField");
        imports.add(root + ".fields." + model.name() + "Fields");
        StringBuilder body = new StringBuilder("/** Typed field accessors; executable filters are deferred. */\n")
                .append("public final class ").append(model.name()).append("Where {\n")
                .append("    private ").append(model.name()).append("Where() {}\n");
        for (ValidatedField field : model.fields()) {
            importsFor(imports, field, root);
            body.append("\n    public static TuprelField<").append(javaType(field, true))
                    .append("> ").append(field.name()).append("() {\n        return ")
                    .append(model.name()).append("Fields.")
                    .append(field.name().toUpperCase(Locale.ROOT)).append(";\n    }\n");
        }
        body.append("}\n");
        return source(root + ".where", imports, body.toString());
    }

    private static String renderSchema(String root, List<ValidatedModel> models) {
        Set<String> imports = new TreeSet<>();
        imports.add("java.util.List");
        for (ValidatedModel model : models) {
            imports.add(root + ".model." + model.name());
            imports.add(root + ".create." + model.name() + "Create");
            imports.add(root + ".update." + model.name() + "Update");
            imports.add(root + ".fields." + model.name() + "Fields");
        }
        StringBuilder body = new StringBuilder("/** Generated schema descriptors; no database operations. */\n")
                .append("public final class TuprelSchema {\n");
        for (ValidatedModel model : models) {
            body.append("    public static final TuprelModel<").append(model.name()).append(", ")
                    .append(model.name()).append("Create, ").append(model.name()).append("Update> ")
                    .append(model.name().toUpperCase(Locale.ROOT)).append(" = new TuprelModel<>(")
                    .append(quote(model.name())).append(", List.of(");
            for (int index = 0; index < model.fields().size(); index++) {
                if (index > 0) {
                    body.append(", ");
                }
                body.append(model.name()).append("Fields.")
                        .append(model.fields().get(index).name().toUpperCase(Locale.ROOT));
            }
            body.append("));\n");
        }
        body.append("\n    private TuprelSchema() {}\n}\n");
        return source(root, imports, body.toString());
    }

    private static String renderInputSupport(String root) {
        return source(root, Set.of(), """
                /** Presence and value are independent: an optional field may be present with null. */
                public record TuprelInput<T>(boolean present, T value) {
                    public TuprelInput {
                        if (!present && value != null) {
                            throw new IllegalArgumentException("Absent input cannot carry a value");
                        }
                    }

                    public static <T> TuprelInput<T> absent() {
                        return new TuprelInput<>(false, null);
                    }

                    public static <T> TuprelInput<T> of(T value) {
                        return new TuprelInput<>(true, value);
                    }
                }
                """);
    }

    private static String renderFieldSupport(String root) {
        return source(root, Set.of("java.util.Objects"), """
                /** Declarative field metadata; it does not execute a query. */
                public record TuprelField<T>(String name, String schemaType, Cardinality cardinality,
                        String relationTarget) {
                    public TuprelField {
                        Objects.requireNonNull(name, "name");
                        Objects.requireNonNull(schemaType, "schemaType");
                        Objects.requireNonNull(cardinality, "cardinality");
                    }

                    public enum Cardinality { REQUIRED, OPTIONAL, LIST }
                }
                """);
    }

    private static String renderModelSupport(String root) {
        return source(root, Set.of("java.util.List", "java.util.Objects"), """
                /** Typed model descriptor; database operations are deferred. */
                public record TuprelModel<M, C, U>(String name, List<TuprelField<?>> fields) {
                    public TuprelModel {
                        Objects.requireNonNull(name, "name");
                        fields = List.copyOf(fields);
                    }
                }
                """);
    }

    private static String renderBytes(String root) {
        return source(root, Set.of("java.util.Arrays", "java.util.Objects"), """
                /** Immutable byte value with content equality. */
                public final class TuprelBytes {
                    private final byte[] value;

                    public TuprelBytes(byte[] value) {
                        this.value = Objects.requireNonNull(value, "value").clone();
                    }

                    public byte[] value() {
                        return value.clone();
                    }

                    @Override public boolean equals(Object other) {
                        return other instanceof TuprelBytes bytes && Arrays.equals(value, bytes.value);
                    }

                    @Override public int hashCode() {
                        return Arrays.hashCode(value);
                    }

                    @Override public String toString() {
                        return "TuprelBytes[" + value.length + " bytes]";
                    }
                }
                """);
    }

    private static String renderJson(String root) {
        return source(root, Set.of("java.util.Objects"), """
                /** Immutable raw JSON text; parsing and database binding are deferred. */
                public record TuprelJson(String text) {
                    public TuprelJson {
                        Objects.requireNonNull(text, "text");
                    }
                }
                """);
    }
}
