package dev.tuprel.codegen;

import dev.tuprel.schema.SourceSpan;
import dev.tuprel.schema.ast.SchemaDocument;
import dev.tuprel.schema.model.RelationGraph;
import dev.tuprel.schema.model.RelationGraph.RelationLink;
import dev.tuprel.schema.model.ValidatedSchema;
import dev.tuprel.schema.model.ValidatedSchema.ResolvedType;
import dev.tuprel.schema.model.ValidatedSchema.TypeKind;
import dev.tuprel.schema.model.ValidatedSchema.ValidatedEnum;
import dev.tuprel.schema.model.ValidatedSchema.ValidatedField;
import dev.tuprel.schema.model.ValidatedSchema.ValidatedModel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import javax.lang.model.SourceVersion;

/**
 * Renders a validated Tuprel schema into deterministic Java 21 sources.
 *
 * <p>Model values, enums, inputs, field metadata and {@code TuprelSchema} depend only on the
 * JDK. Typed columns ({@code where}, {@code order}), model clients and {@code TuprelClient}
 * compile against {@code tuprel-runtime}. The generator itself never depends on the runtime.
 */
public final class JavaCodeGenerator {
    private static final String HEADER = "// Generated by Tuprel. Do not edit.\n";
    private static final String GENERATED = "@javax.annotation.processing.Generated(\"dev.tuprel.codegen\")\n";
    /** Model and field names become quoted PostgreSQL identifiers, limited to 63 bytes. */
    private static final int MAX_SQL_IDENTIFIER = 63;
    private static final Set<String> RESERVED_TYPES = Set.of(
            "BigDecimal", "Boolean", "Byte", "Character", "Class", "Double", "Float",
            "Instant", "Integer", "List", "LocalDate", "LocalDateTime", "LocalTime",
            "Long", "Object", "Objects", "Short", "String", "TuprelBytes", "TuprelField",
            "TuprelInput", "TuprelJson", "TuprelModel", "TuprelRelation", "TuprelSchema", "TuprelClient", "UUID");
    private static final Set<String> RESERVED_MEMBERS = Set.of(
            "build", "builder", "clone", "equals", "finalize", "getClass", "hashCode",
            "notify", "notifyAll", "toString", "wait");

    /** Generates source in memory; no output tree is touched. */
    public JavaGenerationResult generate(ValidatedSchema schema) {
        Objects.requireNonNull(schema, "schema");
        List<GenerationDiagnostic> diagnostics = inspect(schema);
        if (!diagnostics.isEmpty()) {
            return new JavaGenerationResult(Optional.empty(), diagnostics);
        }
        String root = ((SchemaDocument.StringLiteral)
                schema.generator().orElseThrow().properties().get("package")).value();
        Map<String, String> files = new TreeMap<>();
        put(files, root, "TuprelInput", renderInputSupport(root));
        put(files, root, "TuprelField", renderFieldSupport(root));
        put(files, root, "TuprelModel", renderModelSupport(root));
        put(files, root, "TuprelBytes", renderBytes(root));
        put(files, root, "TuprelJson", renderJson(root));
        put(files, root, "TuprelSchema", renderSchema(root, schema.models()));
        put(files, root, "TuprelRelation", renderRelationSupport(root));
        Set<String> schemaNames = schemaNames(schema);
        RelationGraph graph = schema.relations();
        Map<String, ValidatedModel> models = new HashMap<>();
        schema.models().forEach(model -> models.put(model.name(), model));
        put(files, root, "TuprelClient", renderRootClient(root, schema.models(), schemaNames));
        for (ValidatedEnum declaration : schema.enums()) {
            put(files, root + ".model", declaration.name(), renderEnum(root, declaration));
        }
        for (ValidatedModel model : schema.models()) {
            put(files, root + ".model", model.name(), renderModel(root, model, graph, schemaNames));
            if (operationallySupported(model)) {
                put(files, root + ".metadata", model.name() + "Metadata", renderMetadata(root, model, schemaNames));
                List<RelationLink> includable = includable(model, graph, models);
                if (!includable.isEmpty()) {
                    put(files, root + ".include", model.name() + "Include",
                            renderInclude(root, model, graph, includable, schemaNames));
                }
            }
            put(files, root + ".create", model.name() + "Create", renderInput(root, model, false));
            put(files, root + ".update", model.name() + "Update", renderInput(root, model, true));
            put(files, root + ".fields", model.name() + "Fields", renderFields(root, model));
            put(files, root + ".where", model.name() + "Where", renderWhere(root, model, schemaNames));
            put(files, root + ".order", model.name() + "Order", renderOrder(root, model, schemaNames));
            if (operationallySupported(model)) {
                put(files, root + ".client", model.name() + "Client", renderClient(root, model, schemaNames));
            }
        }
        return new JavaGenerationResult(Optional.of(new GeneratedJavaSources(files)), List.of());
    }

    private static List<GenerationDiagnostic> inspect(ValidatedSchema schema) {
        List<GenerationDiagnostic> diagnostics = new ArrayList<>();
        if (schema.generator().isEmpty()) {
            diagnostics.add(diagnostic("001", "Java generation requires generator java with package.",
                    schema.syntax().span()));
            return diagnostics;
        }
        var config = schema.generator().orElseThrow();
        if (!(config.properties().get("package") instanceof SchemaDocument.StringLiteral literal)
                || !literal.value().matches("[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*")) {
            diagnostics.add(diagnostic("002", "Generator package must be a valid Java package name.",
                    config.span()));
            return diagnostics;
        }
        String packageName = literal.value();
        if (packageName.equals("java") || packageName.startsWith("java.")) {
            diagnostics.add(diagnostic("009", "Generator package cannot use the reserved java namespace.",
                    config.span()));
        }
        int segmentStart = 0;
        for (int index = 0; index <= packageName.length(); index++) {
            if (index == packageName.length() || packageName.charAt(index) == '.') {
                String segment = packageName.substring(segmentStart, index);
                if (!identifier(segment)) {
                    diagnostics.add(diagnostic("002", "Generator package contains an invalid Java identifier.",
                            config.span()));
                }
                if (deviceName(segment)) {
                    diagnostics.add(diagnostic("008", "Generator package segment is a reserved filesystem name: "
                            + segment, config.span()));
                }
                segmentStart = index + 1;
            }
        }
        Set<String> typeNames = new HashSet<>();
        Set<String> derivedNames = new HashSet<>();
        Set<String> modelNames = new HashSet<>();
        Set<String> enumNames = new HashSet<>();
        schema.models().forEach(model -> modelNames.add(model.name()));
        schema.enums().forEach(enumeration -> enumNames.add(enumeration.name()));
        for (ValidatedModel model : schema.models()) {
            for (String suffix : List.of("Create", "Update", "Fields", "Where", "Order", "Client", "Include",
                    "Metadata")) {
                derivedNames.add((model.name() + suffix).toLowerCase(Locale.ROOT));
            }
        }
        for (ValidatedModel model : schema.models()) {
            inspectType(model.name(), model.span(), typeNames, diagnostics);
            if (derivedNames.contains(model.name().toLowerCase(Locale.ROOT))) {
                diagnostics.add(diagnostic("007", "Java type name conflicts with a generated companion: "
                        + model.name(), model.span()));
            }
            if (model.name().length() > MAX_SQL_IDENTIFIER) {
                diagnostics.add(diagnostic("014", "Model name is used as the table name and exceeds the "
                        + MAX_SQL_IDENTIFIER + "-character PostgreSQL identifier limit: " + model.name(),
                        model.span()));
            }
            Set<String> fieldNames = new HashSet<>();
            Set<String> constantNames = new HashSet<>();
            for (ValidatedField field : model.fields()) {
                if (!identifier(field.name()) || deviceName(field.name())) {
                    diagnostics.add(diagnostic("010", "Field name is not a safe Java identifier.",
                            field.span()));
                }
                if (field.type().kind() != TypeKind.MODEL && field.name().length() > MAX_SQL_IDENTIFIER) {
                    diagnostics.add(diagnostic("014", "Field name is used as the column name and exceeds the "
                            + MAX_SQL_IDENTIFIER + "-character PostgreSQL identifier limit: " + field.name(),
                            field.span()));
                }
                if (!fieldNames.add(field.name().toLowerCase(Locale.ROOT))
                        || !constantNames.add(field.name().toUpperCase(Locale.ROOT))) {
                    diagnostics.add(diagnostic("004", "Java field name collides after case folding: "
                            + field.name(), field.span()));
                }
                if (RESERVED_MEMBERS.contains(field.name())) {
                    diagnostics.add(diagnostic("005", "Java field name conflicts with a generated or inherited method: "
                            + field.name(), field.span()));
                }
                if (field.type().kind() == TypeKind.SCALAR && scalar(field.type(), false) == null) {
                    diagnostics.add(diagnostic("006", "Unsupported Java scalar: " + field.type().name(),
                            field.span()));
                } else if (!identifier(field.type().name())
                        || (field.type().kind() == TypeKind.MODEL
                                && !modelNames.contains(field.type().name()))
                        || (field.type().kind() == TypeKind.ENUM
                                && !enumNames.contains(field.type().name()))) {
                    diagnostics.add(diagnostic("011", "Field has an invalid or undeclared Java type.",
                            field.span()));
                }
            }
        }
        for (ValidatedEnum enumeration : schema.enums()) {
            inspectType(enumeration.name(), enumeration.span(), typeNames, diagnostics);
            Set<String> values = new HashSet<>();
            for (String value : enumeration.values()) {
                if (!identifier(value) || !values.add(value)) {
                    diagnostics.add(diagnostic("012", "Enum contains an invalid or duplicate Java value.",
                            enumeration.span()));
                }
            }
            if (derivedNames.contains(enumeration.name().toLowerCase(Locale.ROOT))) {
                diagnostics.add(diagnostic("007", "Java type name conflicts with a generated companion: "
                        + enumeration.name(), enumeration.span()));
            }
        }
        return diagnostics;
    }

    private static void inspectType(String name, SourceSpan span, Set<String> names,
            List<GenerationDiagnostic> diagnostics) {
        if (!identifier(name)) {
            diagnostics.add(diagnostic("013", "Model or enum name is not a safe Java identifier.", span));
        }
        if (RESERVED_TYPES.contains(name) || deviceName(name)
                || !names.add(name.toLowerCase(Locale.ROOT))) {
            diagnostics.add(diagnostic("003", "Java type name conflicts with another generated or JDK type: "
                    + name, span));
        }
    }

    private static boolean identifier(String name) {
        return name.matches("[A-Za-z_][A-Za-z0-9_]*")
                && SourceVersion.isIdentifier(name) && !SourceVersion.isKeyword(name);
    }

    private static boolean deviceName(String name) {
        return name.toUpperCase(Locale.ROOT).matches("CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9]");
    }

    private static GenerationDiagnostic diagnostic(String suffix, String message, SourceSpan span) {
        return new GenerationDiagnostic("TUPREL-CODEGEN-" + suffix, message, span);
    }

    private static void put(Map<String, String> files, String packageName, String name, String content) {
        files.put(packageName.replace('.', '/') + "/" + name + ".java", content);
    }

    private static String source(String packageName, Set<String> imports, String body) {
        StringBuilder result = new StringBuilder(HEADER).append("package ").append(packageName)
                .append(";\n\n");
        for (String item : new TreeSet<>(imports)) {
            result.append("import ").append(item).append(";\n");
        }
        if (!imports.isEmpty()) {
            result.append('\n');
        }
        return result.append(annotated(body)).toString();
    }

    /**
     * Marks the top-level type as generated so static analysis configured to skip generated
     * code, such as Error Prone's {@code disableWarningsInGeneratedCode}, recognises it. The
     * annotation is JDK-only, source-retained and fully qualified, so no schema name can clash.
     */
    private static String annotated(String body) {
        int declaration = body.startsWith("public ") ? 0 : body.indexOf("\npublic ") + 1;
        if (declaration == 0 && !body.startsWith("public ")) {
            throw new IllegalStateException("Generated source has no top-level public type");
        }
        return body.substring(0, declaration) + GENERATED + body.substring(declaration);
    }

    private static String scalar(ResolvedType type, boolean boxed) {
        if (type.kind() != TypeKind.SCALAR) {
            return type.name();
        }
        return switch (type.name()) {
            case "String" -> "String";
            case "Boolean" -> boxed ? "Boolean" : "boolean";
            case "Short" -> boxed ? "Short" : "short";
            case "Int" -> boxed ? "Integer" : "int";
            case "Long" -> boxed ? "Long" : "long";
            case "Decimal" -> "BigDecimal";
            case "Float" -> boxed ? "Float" : "float";
            case "Double" -> boxed ? "Double" : "double";
            case "UUID" -> "UUID";
            case "Instant" -> "Instant";
            case "LocalDateTime" -> "LocalDateTime";
            case "LocalDate" -> "LocalDate";
            case "LocalTime" -> "LocalTime";
            case "Bytes" -> "TuprelBytes";
            case "Json" -> "TuprelJson";
            default -> null;
        };
    }

    private static String javaType(ValidatedField field, boolean boxed) {
        String element = scalar(field.type(), boxed || field.cardinality() != SchemaDocument.Cardinality.REQUIRED);
        return field.cardinality() == SchemaDocument.Cardinality.LIST
                ? "List<" + scalar(field.type(), true) + ">" : element;
    }

    private static void importsFor(Set<String> imports, ValidatedField field, String root) {
        if (field.cardinality() == SchemaDocument.Cardinality.LIST) {
            imports.add("java.util.List");
        }
        if (field.type().kind() == TypeKind.ENUM || field.type().kind() == TypeKind.MODEL) {
            imports.add(root + ".model." + field.type().name());
            return;
        }
        switch (field.type().name()) {
            case "Decimal" -> imports.add("java.math.BigDecimal");
            case "UUID" -> imports.add("java.util.UUID");
            case "Instant", "LocalDate", "LocalDateTime", "LocalTime" ->
                    imports.add("java.time." + field.type().name());
            case "Bytes", "Json" -> imports.add(root + ".Tuprel" + field.type().name());
            default -> { }
        }
    }

    private static String quote(String value) {
        StringBuilder quoted = new StringBuilder("\"");
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            switch (character) {
                case '\\' -> quoted.append("\\\\");
                case '"' -> quoted.append("\\\"");
                case '\n' -> quoted.append("\\n");
                case '\r' -> quoted.append("\\r");
                case '\t' -> quoted.append("\\t");
                default -> quoted.append(character);
            }
        }
        return quoted.append('"').toString();
    }

    private static String renderEnum(String root, ValidatedEnum enumeration) {
        return source(root + ".model", Set.of(), "public enum " + enumeration.name() + " {\n    "
                + String.join(",\n    ", enumeration.values()) + "\n}\n");
    }

    private static String renderModel(String root, ValidatedModel model, RelationGraph graph,
            Set<String> schemaNames) {
        Set<String> imports = new TreeSet<>();
        TypeRefs refs = new TypeRefs(imports, schemaNames);
        List<ValidatedField> fields = model.fields().stream()
                .filter(field -> field.type().kind() != TypeKind.MODEL).toList();
        List<RelationLink> relations = relations(model, graph);
        for (ValidatedField field : fields) {
            importsFor(imports, field, root);
            imports.remove(root + ".model." + field.type().name());
            if (field.cardinality() != SchemaDocument.Cardinality.OPTIONAL
                    && !javaType(field, false).matches("boolean|short|int|long|float|double")) {
                imports.add("java.util.Objects");
            }
        }
        if (!relations.isEmpty()) {
            imports.add(root + ".TuprelRelation");
            imports.add("java.util.Objects");
        }
        if (relations.stream().anyMatch(RelationLink::toMany)) {
            imports.add("java.util.List");
        }
        StringBuilder body = new StringBuilder();
        if (relations.isEmpty()) {
            body.append("/** Immutable value for model ").append(model.name())
                    .append("; relations are represented by metadata only. */\n");
        } else {
            body.append("/**\n * Immutable value for model ").append(model.name()).append(".\n *\n")
                    .append(" * <p>Relation components hold a value only when a query includes them; reading an\n")
                    .append(" * unloaded relation fails instead of querying the database.\n */\n");
        }
        body.append("public record ").append(model.name()).append("(");
        List<String> components = new ArrayList<>();
        for (ValidatedField field : fields) {
            components.add(javaType(field, false) + " " + field.name());
        }
        for (RelationLink link : relations) {
            components.add(relationType(link, refs) + " " + link.field());
        }
        body.append(String.join(", ", components)).append(") {\n");
        body.append("    public ").append(model.name()).append(" {\n");
        for (ValidatedField field : fields) {
            if (field.cardinality() == SchemaDocument.Cardinality.LIST) {
                body.append("        ").append(field.name()).append(" = List.copyOf(")
                        .append(field.name()).append(");\n");
            } else if (field.cardinality() == SchemaDocument.Cardinality.REQUIRED
                    && !javaType(field, false).matches("boolean|short|int|long|float|double")) {
                body.append("        Objects.requireNonNull(").append(field.name()).append(", ")
                        .append(quote(field.name())).append(");\n");
            }
        }
        for (RelationLink link : relations) {
            body.append("        Objects.requireNonNull(").append(link.field()).append(", ")
                    .append(quote(link.field())).append(");\n");
        }
        body.append("    }\n");
        if (!relations.isEmpty()) {
            body.append("\n    /** Creates a value whose relations are not loaded. */\n    public ")
                    .append(model.name()).append('(')
                    .append(String.join(", ", components.subList(0, fields.size()))).append(") {\n        this(");
            List<String> arguments = new ArrayList<>();
            fields.forEach(field -> arguments.add(field.name()));
            for (RelationLink link : relations) {
                arguments.add("TuprelRelation.notLoaded(" + quote(model.name()) + ", " + quote(link.field()) + ")");
            }
            body.append(String.join(", ", arguments)).append(");\n    }\n");
        }
        return source(root + ".model", imports, body.append("}\n").toString());
    }

    /** Relation fields of a model in declaration order. */
    private static List<RelationLink> relations(ValidatedModel model, RelationGraph graph) {
        return model.fields().stream()
                .filter(field -> field.type().kind() == TypeKind.MODEL)
                .map(field -> graph.link(model.name(), field.name()).orElseThrow(
                        () -> new IllegalStateException("A validated relation field has no link")))
                .toList();
    }

    private static String relationType(RelationLink link, TypeRefs refs) {
        String value;
        if (link.toMany()) {
            value = "List<" + link.target() + ">";
        } else if (link.side() == RelationGraph.Side.OWNING
                && link.cardinality() == SchemaDocument.Cardinality.REQUIRED) {
            value = link.target();
        } else {
            value = refs.use("java.util.Optional") + "<" + link.target() + ">";
        }
        return "TuprelRelation<" + value + ">";
    }

    private static String renderInput(String root, ValidatedModel model, boolean update) {
        String suffix = update ? "Update" : "Create";
        String name = model.name() + suffix;
        List<ValidatedField> fields = model.fields().stream()
                .filter(field -> field.type().kind() != TypeKind.MODEL
                        && (!update || (!field.id() && !field.version())))
                .toList();
        Set<String> imports = new TreeSet<>();
        imports.add(root + ".TuprelInput");
        for (ValidatedField field : fields) {
            importsFor(imports, field, root);
            if (field.cardinality() == SchemaDocument.Cardinality.REQUIRED) {
                imports.add("java.util.Objects");
            }
        }
        StringBuilder body = new StringBuilder("/** Immutable ").append(suffix.toLowerCase(Locale.ROOT))
                .append(" input for ").append(model.name()).append(". */\npublic final class ")
                .append(name).append(" {\n");
        for (ValidatedField field : fields) {
            body.append("    private final TuprelInput<").append(javaType(field, true)).append("> ")
                    .append(field.name()).append(";\n");
        }
        body.append("\n    private ").append(name).append("(Builder builder) {\n");
        for (ValidatedField field : fields) {
            body.append("        this.").append(field.name()).append(" = builder.")
                    .append(field.name()).append(";\n");
        }
        body.append("    }\n\n    public static Builder builder() {\n        return new Builder();\n    }\n");
        for (ValidatedField field : fields) {
            body.append("\n    public TuprelInput<").append(javaType(field, true)).append("> ")
                    .append(field.name()).append("() {\n        return ").append(field.name())
                    .append(";\n    }\n");
        }
        body.append("\n    public static final class Builder {\n");
        for (ValidatedField field : fields) {
            body.append("        private TuprelInput<").append(javaType(field, true)).append("> ")
                    .append(field.name()).append(" = TuprelInput.absent();\n");
        }
        body.append("\n        private Builder() {}\n");
        for (ValidatedField field : fields) {
            body.append("\n        public Builder ").append(field.name()).append('(')
                    .append(javaType(field, true)).append(" value) {\n            this.")
                    .append(field.name()).append(" = TuprelInput.of(");
            if (field.cardinality() == SchemaDocument.Cardinality.LIST) {
                body.append("List.copyOf(value)");
            } else if (field.cardinality() == SchemaDocument.Cardinality.REQUIRED) {
                body.append("Objects.requireNonNull(value, ").append(quote(field.name())).append(')');
            } else {
                body.append("value");
            }
            body.append(");\n            return this;\n        }\n");
        }
        body.append("\n        public ").append(name).append(" build() {\n");
        if (!update) {
            for (ValidatedField field : fields) {
                if (field.cardinality() == SchemaDocument.Cardinality.REQUIRED
                        && field.defaultValue().isEmpty()) {
                    body.append("            if (!").append(field.name()).append(".present()) {\n")
                            .append("                throw new IllegalStateException(")
                            .append(quote("Required create field missing: " + field.name()))
                            .append(");\n            }\n");
                }
            }
        }
        body.append("            return new ").append(name).append("(this);\n        }\n")
                .append("    }\n}\n");
        return source(root + (update ? ".update" : ".create"), imports, body.toString());
    }

    private static String renderFields(String root, ValidatedModel model) {
        Set<String> imports = new TreeSet<>();
        imports.add(root + ".TuprelField");
        StringBuilder body = new StringBuilder("/** Structural fields for ")
                .append(model.name()).append("; no query execution. */\npublic final class ")
                .append(model.name()).append("Fields {\n");
        for (ValidatedField field : model.fields()) {
            importsFor(imports, field, root);
            body.append("    public static final TuprelField<").append(javaType(field, true))
                    .append("> ").append(field.name().toUpperCase(Locale.ROOT))
                    .append(" = new TuprelField<>(").append(quote(field.name())).append(", ")
                    .append(quote(field.type().name())).append(", TuprelField.Cardinality.")
                    .append(field.cardinality().name()).append(", ")
                    .append(field.type().kind() == TypeKind.MODEL
                            ? quote(field.type().name()) : "null")
                    .append(");\n");
        }
        body.append("\n    private ").append(model.name()).append("Fields() {}\n}\n");
        return source(root + ".fields", imports, body.toString());
    }

    private static final String RUNTIME = "dev.tuprel.runtime.";
    private static final String QUERY = "dev.tuprel.runtime.query.";

    /**
     * Imports a type by simple name unless a schema model or enum uses the same simple name, in
     * which case the fully qualified name is used, so runtime types never reserve model names.
     */
    private record TypeRefs(Set<String> imports, Set<String> schemaNames) {
        String use(String qualifiedName) {
            String simple = qualifiedName.substring(qualifiedName.lastIndexOf('.') + 1);
            if (schemaNames.contains(simple)) {
                return qualifiedName;
            }
            imports.add(qualifiedName);
            return simple;
        }
    }

    private static Set<String> schemaNames(ValidatedSchema schema) {
        Set<String> names = new HashSet<>();
        schema.models().forEach(model -> names.add(model.name()));
        schema.enums().forEach(enumeration -> names.add(enumeration.name()));
        return names;
    }

    /** A field maps to a column when it is a singular scalar or enum other than Json. */
    private static boolean operationalField(ValidatedField field) {
        return field.type().kind() != TypeKind.MODEL
                && field.cardinality() != SchemaDocument.Cardinality.LIST
                && !field.type().name().equals("Json");
    }

    /** A model gets a client when every non-relation field maps to a column. */
    private static boolean operationallySupported(ValidatedModel model) {
        return model.fields().stream().allMatch(field ->
                field.type().kind() == TypeKind.MODEL || operationalField(field));
    }

    private static List<ValidatedField> columns(ValidatedModel model) {
        return model.fields().stream().filter(JavaCodeGenerator::operationalField).toList();
    }

    private static String fieldType(ValidatedField field, String model, TypeRefs refs) {
        String value = javaType(field, true);
        if (field.type().kind() == TypeKind.ENUM) {
            return refs.use(QUERY + "Field") + "<" + model + ", " + value + ">";
        }
        return switch (field.type().name()) {
            case "String" -> refs.use(QUERY + "TextField") + "<" + model + ">";
            case "Boolean", "UUID", "Bytes" -> refs.use(QUERY + "Field") + "<" + model + ", " + value + ">";
            default -> refs.use(QUERY + "ComparableField") + "<" + model + ", " + value + ">";
        };
    }

    private static String fieldFactory(ValidatedField field, String model, TypeRefs refs) {
        String arguments = quote(field.name()) + ", "
                + (field.cardinality() == SchemaDocument.Cardinality.OPTIONAL) + ", "
                + model + "::" + field.name();
        if (field.type().kind() == TypeKind.ENUM) {
            return refs.use(QUERY + "Field") + ".enumeration(" + arguments + ", "
                    + field.type().name() + "::valueOf)";
        }
        String comparable = refs.use(QUERY + "ComparableField");
        return switch (field.type().name()) {
            case "String" -> refs.use(QUERY + "TextField") + ".text(" + arguments + ")";
            case "Boolean" -> refs.use(QUERY + "Field") + ".bool(" + arguments + ")";
            case "UUID" -> refs.use(QUERY + "Field") + ".uuid(" + arguments + ")";
            case "Bytes" -> refs.use(QUERY + "Field") + ".bytes(" + arguments
                    + ", TuprelBytes::new, TuprelBytes::value)";
            case "Short" -> comparable + ".int16(" + arguments + ")";
            case "Int" -> comparable + ".int32(" + arguments + ")";
            case "Long" -> comparable + ".int64(" + arguments + ")";
            case "Float" -> comparable + ".float32(" + arguments + ")";
            case "Double" -> comparable + ".float64(" + arguments + ")";
            case "Decimal" -> comparable + ".decimal(" + arguments + ")";
            case "Instant" -> comparable + ".instant(" + arguments + ")";
            case "LocalDateTime" -> comparable + ".dateTime(" + arguments + ")";
            case "LocalDate" -> comparable + ".date(" + arguments + ")";
            case "LocalTime" -> comparable + ".time(" + arguments + ")";
            default -> throw new IllegalArgumentException("Unsupported column type: " + field.type().name());
        };
    }

    private static String renderWhere(String root, ValidatedModel model, Set<String> schemaNames) {
        Set<String> imports = new TreeSet<>();
        TypeRefs refs = new TypeRefs(imports, schemaNames);
        imports.add(root + ".model." + model.name());
        List<ValidatedField> columns = columns(model);
        StringBuilder constants = new StringBuilder();
        StringBuilder accessors = new StringBuilder();
        for (ValidatedField field : columns) {
            importsFor(imports, field, root);
            String type = fieldType(field, model.name(), refs);
            String constant = field.name().toUpperCase(Locale.ROOT);
            constants.append("    private static final ").append(type).append(' ').append(constant)
                    .append(" =\n            ").append(fieldFactory(field, model.name(), refs)).append(";\n");
            accessors.append("\n    /** Column {@code ").append(field.name()).append("}. */\n")
                    .append("    public static ").append(type).append(' ').append(field.name())
                    .append("() {\n        return ").append(constant).append(";\n    }\n");
        }
        StringBuilder body = new StringBuilder("/**\n * Typed columns of {@code ").append(model.name())
                .append("} for filters and projections. Each column is named exactly like its\n")
                .append(" * schema field. Relation, list and Json fields are not columns here.\n */\n")
                .append("public final class ").append(model.name()).append("Where {\n")
                .append(constants);
        if (!columns.isEmpty()) {
            body.append('\n');
        }
        body.append("    private ").append(model.name()).append("Where() {}\n").append(accessors).append("}\n");
        return source(root + ".where", imports, body.toString());
    }

    private static String renderOrder(String root, ValidatedModel model, Set<String> schemaNames) {
        Set<String> imports = new TreeSet<>();
        TypeRefs refs = new TypeRefs(imports, schemaNames);
        StringBuilder body = new StringBuilder("/** Orderable columns of {@code ").append(model.name())
                .append("}. */\npublic final class ").append(model.name()).append("Order {\n    private ")
                .append(model.name()).append("Order() {}\n");
        for (ValidatedField field : columns(model)) {
            imports.add(root + ".model." + model.name());
            imports.add(root + ".where." + model.name() + "Where");
            body.append("\n    /** Column {@code ").append(field.name()).append("}. */\n")
                    .append("    public static ").append(refs.use(QUERY + "Sortable")).append('<')
                    .append(model.name()).append("> ").append(field.name()).append("() {\n        return ")
                    .append(model.name()).append("Where.").append(field.name()).append("();\n    }\n");
        }
        return source(root + ".order", imports, body.append("}\n").toString());
    }

    /** A type variable name that no schema model or enum shadows. */
    private static String typeVariable(Set<String> schemaNames, String preferred) {
        String name = preferred;
        for (int suffix = 0; schemaNames.contains(name); suffix++) {
            name = preferred + suffix;
        }
        return name;
    }

    private static String renderRootClient(String root, List<ValidatedModel> models, Set<String> schemaNames) {
        Set<String> imports = new TreeSet<>();
        TypeRefs refs = new TypeRefs(imports, schemaNames);
        String database = refs.use(RUNTIME + "TuprelDatabase");
        String objects = refs.use("java.util.Objects");
        String function = refs.use("java.util.function.Function");
        String options = refs.use(RUNTIME + "TransactionOptions");
        String result = typeVariable(schemaNames, "T");
        List<ValidatedModel> operational = models.stream()
                .filter(JavaCodeGenerator::operationallySupported).toList();
        StringBuilder body = new StringBuilder("""
                /**
                 * Entry point to the generated model clients. It holds no connection: outside a
                 * transaction every client operation obtains and releases its own connection from the
                 * runtime's DataSource. Models with list or Json fields have no client yet.
                 */
                public final class TuprelClient {
                """);
        body.append("    private final ").append(database).append(" database;\n");
        for (ValidatedModel model : operational) {
            imports.add(root + ".client." + model.name() + "Client");
            body.append("    private final ").append(model.name()).append("Client ")
                    .append(lowerFirst(model.name())).append(";\n");
        }
        body.append("\n    /** Creates the clients over an explicit runtime; the caller owns its DataSource. */\n")
                .append("    public TuprelClient(").append(database).append(" database) {\n")
                .append("        this.database = ").append(objects).append(".requireNonNull(database, \"database\");\n");
        for (ValidatedModel model : operational) {
            body.append("        this.").append(lowerFirst(model.name())).append(" = new ")
                    .append(model.name()).append("Client(database);\n");
        }
        body.append("    }\n");
        body.append("\n    /**\n     * Runs work in one transaction with connection defaults and commits when it returns;\n")
                .append("     * an exception rolls it back. Called on a client passed to such work, it runs a nested\n")
                .append("     * block with a savepoint. The client passed to the work is unusable afterwards.\n     */\n")
                .append("    public <").append(result).append("> ").append(result).append(" transaction(")
                .append(function).append("<TuprelClient, ").append(result).append("> work) {\n")
                .append("        ").append(objects).append(".requireNonNull(work, \"work\");\n")
                .append("        return database.transaction(transaction -> work.apply(new TuprelClient(transaction)));\n")
                .append("    }\n");
        body.append("\n    /** Runs work in one transaction with the given isolation, access mode and deadline. */\n")
                .append("    public <").append(result).append("> ").append(result).append(" transaction(")
                .append(options).append(" options, ").append(function).append("<TuprelClient, ").append(result)
                .append("> work) {\n")
                .append("        ").append(objects).append(".requireNonNull(work, \"work\");\n")
                .append("        return database.transaction(options, transaction -> work.apply(new TuprelClient(transaction)));\n")
                .append("    }\n");
        for (ValidatedModel model : operational) {
            body.append("\n    /** Operations on model {@code ").append(model.name()).append("}. */\n")
                    .append("    public ").append(model.name()).append("Client ")
                    .append(lowerFirst(model.name())).append("() {\n        return ")
                    .append(lowerFirst(model.name())).append(";\n    }\n");
        }
        return source(root, imports, body.append("}\n").toString());
    }

    private static Optional<ValidatedField> versionField(ValidatedModel model) {
        return columns(model).stream().filter(ValidatedField::version).findFirst();
    }

    private static String renderMetadata(String root, ValidatedModel model, Set<String> schemaNames) {
        String name = model.name();
        List<ValidatedField> columns = columns(model);
        ValidatedField id = columns.stream().filter(ValidatedField::id).findFirst()
                .orElseThrow(() -> new IllegalStateException("A validated model has exactly one @id field"));
        Set<String> imports = new TreeSet<>();
        TypeRefs refs = new TypeRefs(imports, schemaNames);
        imports.add(root + ".model." + name);
        imports.add(root + ".where." + name + "Where");
        importsFor(imports, id, root);
        String where = name + "Where";
        String table = refs.use(QUERY + "ModelTable");
        StringBuilder mapper = new StringBuilder();
        StringBuilder fieldList = new StringBuilder();
        for (int index = 0; index < columns.size(); index++) {
            String separator = index == 0 ? "" : ",\n                    ";
            mapper.append(separator).append(where).append('.').append(columns.get(index).name())
                    .append("().read(row)");
            fieldList.append(separator).append(where).append('.').append(columns.get(index).name()).append("()");
        }
        Optional<ValidatedField> version = versionField(model);
        StringBuilder body = new StringBuilder("/**\n * Table mapping of model {@code ").append(name)
                .append("}: table {@code \"").append(name)
                .append("\"}, with each column named exactly like its field.\n */\n")
                .append("public final class ").append(name).append("Metadata {\n")
                .append("    /** Table, identifier, ").append(version.isPresent() ? "version, " : "")
                .append("columns and row mapper. */\n")
                .append("    public static final ").append(table).append('<').append(name).append(", ")
                .append(javaType(id, true)).append("> TABLE = ").append(table)
                .append(version.isPresent() ? ".versioned(" : ".of(").append("\n            ").append(quote(name))
                .append(",\n            ").append(where).append('.').append(id.name()).append("(),\n");
        version.ifPresent(field -> body.append("            ").append(where).append('.').append(field.name())
                .append("(),\n"));
        body.append("            ").append(refs.use("java.util.List")).append(".of(\n                    ")
                .append(fieldList).append("),\n            row -> new ").append(name).append("(\n                    ")
                .append(mapper).append("));\n\n    private ").append(name).append("Metadata() {}\n}\n");
        return source(root + ".metadata", imports, body.toString());
    }

    /** Relations of a model that a query can include: both models have clients and the keys are columns. */
    private static List<RelationLink> includable(ValidatedModel model, RelationGraph graph,
            Map<String, ValidatedModel> models) {
        if (!operationallySupported(model)) {
            return List.of();
        }
        return relations(model, graph).stream()
                .filter(link -> operationallySupported(models.get(link.target()))
                        && columnsExist(model, link.localFields())
                        && columnsExist(models.get(link.target()), link.targetFields()))
                .toList();
    }

    private static boolean columnsExist(ValidatedModel model, List<String> names) {
        return names.stream().allMatch(name -> columns(model).stream().anyMatch(field -> field.name().equals(name)));
    }

    private static String renderInclude(String root, ValidatedModel model, RelationGraph graph,
            List<RelationLink> links, Set<String> schemaNames) {
        String name = model.name();
        Set<String> imports = new TreeSet<>();
        TypeRefs refs = new TypeRefs(imports, schemaNames);
        imports.add(root + ".TuprelRelation");
        imports.add(root + ".model." + name);
        imports.add(root + ".where." + name + "Where");
        String relation = refs.use(QUERY + "Relation");
        String include = refs.use(QUERY + "Include");
        String query = refs.use(QUERY + "Query");
        String operator = refs.use("java.util.function.UnaryOperator");
        String list = refs.use("java.util.List");
        List<ValidatedField> columns = columns(model);
        List<RelationLink> all = relations(model, graph);
        StringBuilder constants = new StringBuilder();
        StringBuilder methods = new StringBuilder();
        for (RelationLink link : links) {
            String target = link.target();
            imports.add(root + ".model." + target);
            imports.add(root + ".where." + target + "Where");
            imports.add(root + ".metadata." + target + "Metadata");
            String factory = link.toMany() ? "toMany"
                    : link.side() == RelationGraph.Side.OWNING
                            && link.cardinality() == SchemaDocument.Cardinality.REQUIRED ? "toOne" : "toOptional";
            List<String> arguments = new ArrayList<>();
            columns.forEach(field -> arguments.add("row." + field.name() + "()"));
            for (RelationLink other : all) {
                arguments.add(other.field().equals(link.field())
                        ? "TuprelRelation.loaded(" + quote(name) + ", " + quote(link.field()) + ", value)"
                        : "row." + other.field() + "()");
            }
            String constant = link.field().toUpperCase(Locale.ROOT);
            constants.append("    private static final ").append(relation).append('<').append(name).append(", ")
                    .append(target).append("> ").append(constant).append(" = ").append(relation).append('.')
                    .append(factory).append("(\n            ").append(quote(name + "." + link.field()))
                    .append(",\n            ").append(list).append(".of(")
                    .append(fieldCalls(name + "Where", link.localFields())).append("),\n            () -> ")
                    .append(target).append("Metadata.TABLE,\n            ").append(list).append(".of(")
                    .append(fieldCalls(target + "Where", link.targetFields())).append("),\n            (row, value) -> new ")
                    .append(name).append('(').append(String.join(", ", arguments)).append("));\n");
            String description = link.toMany()
                    ? "every related {@code " + target + "}, ordered by its identifier unless the nested query orders them"
                    : "the related {@code " + target + "}";
            methods.append("\n    /** Loads {@code ").append(name).append('.').append(link.field()).append("}: ")
                    .append(description).append(". */\n    public static ").append(include).append('<').append(name)
                    .append("> ").append(link.field()).append("() {\n        return ").append(constant)
                    .append(".include();\n    }\n");
            methods.append("\n    /** Loads {@code ").append(name).append('.').append(link.field()).append("} with ")
                    .append(link.toMany() ? "a nested condition, ordering and includes" : "nested includes")
                    .append(". */\n    public static ").append(include).append('<').append(name).append("> ")
                    .append(link.field()).append('(').append(operator).append('<').append(query).append('<')
                    .append(target).append(">> query) {\n        return ").append(constant)
                    .append(".include(query);\n    }\n");
        }
        String body = "/**\n * Relations of {@code " + name
                + "} that a query loads explicitly with {@code include}. Each included\n"
                + " * relation runs one query for all rows together, never one query per row.\n */\n"
                + "public final class " + name + "Include {\n" + constants
                + "\n    private " + name + "Include() {}\n" + methods + "}\n";
        return source(root + ".include", imports, body);
    }

    private static String fieldCalls(String owner, List<String> fields) {
        return String.join(", ", fields.stream().map(field -> owner + "." + field + "()").toList());
    }

    private static String renderClient(String root, ValidatedModel model, Set<String> schemaNames) {
        String name = model.name();
        List<ValidatedField> columns = columns(model);
        ValidatedField id = columns.stream().filter(ValidatedField::id).findFirst()
                .orElseThrow(() -> new IllegalStateException("A validated model has exactly one @id field"));
        Optional<ValidatedField> version = versionField(model);
        Set<String> imports = new TreeSet<>();
        TypeRefs refs = new TypeRefs(imports, schemaNames);
        imports.add(root + ".model." + name);
        imports.add(root + ".create." + name + "Create");
        imports.add(root + ".update." + name + "Update");
        imports.add(root + ".where." + name + "Where");
        imports.add(root + ".metadata." + name + "Metadata");
        importsFor(imports, id, root);
        String where = name + "Where";
        String idType = javaType(id, false);
        String list = refs.use("java.util.List");
        String objects = refs.use("java.util.Objects");
        String optional = refs.use("java.util.Optional");
        String operator = refs.use("java.util.function.UnaryOperator");
        String query = refs.use(QUERY + "Query") + "<" + name + ">";
        String configure = operator + "<" + query + "> query";
        String assignments = refs.use(QUERY + "Assignments") + "<" + name + ">";
        String emptyAssignments = refs.use(QUERY + "Assignments") + ".empty()";
        String emptyQuery = refs.use(QUERY + "Query") + ".all()";
        String condition = refs.use(QUERY + "Condition") + "<" + name + "> where";
        String projected = typeVariable(schemaNames, "R");

        StringBuilder body = new StringBuilder("/**\n * Explicit operations on table {@code \"")
                .append(name).append("\"} for model {@code ").append(name).append("}.\n *\n")
                .append(" * <p>Each method runs one SQL statement with bound parameters, plus one statement per\n")
                .append(" * included relation. Outside a transaction each statement uses its own autocommit\n")
                .append(" * connection. Nothing is cached, tracked or loaded lazily.\n */\n")
                .append("public final class ").append(name).append("Client {\n")
                .append("    private final ").append(refs.use(QUERY + "ModelOperations")).append('<')
                .append(name).append(", ").append(javaType(id, true)).append("> operations;\n\n")
                .append("    /** Creates the client over an explicit runtime; the caller owns its DataSource. */\n")
                .append("    public ").append(name).append("Client(").append(refs.use(RUNTIME + "TuprelDatabase"))
                .append(" database) {\n        this.operations = new ")
                .append(refs.use(QUERY + "ModelOperations")).append("<>(").append(objects)
                .append(".requireNonNull(database, \"database\"), ").append(name).append("Metadata.TABLE);\n    }\n");

        body.append("\n    /** Inserts the present input fields and returns the stored row. */\n")
                .append("    public ").append(name).append(" create(").append(name).append("Create input) {\n")
                .append("        return operations.create(values(input));\n    }\n");
        body.append("\n    /**\n     * Inserts rows with multi-row statements and returns the number of inserted rows;\n")
                .append("     * a batch that needs several statements requires a transaction.\n     */\n")
                .append("    public long createMany(").append(list).append('<').append(name)
                .append("Create> inputs) {\n        ").append(objects).append(".requireNonNull(inputs, \"inputs\");\n")
                .append("        return operations.createMany(inputs.stream().map(")
                .append(name).append("Client::values).toList());\n    }\n");
        body.append("\n    /** Reads the row with the identifier. */\n")
                .append("    public ").append(optional).append('<').append(name).append("> findById(")
                .append(idType).append(" id) {\n        return operations.findById(id);\n    }\n");
        body.append("\n    /** Reads the row with the identifier; the query may only include relations, lock or time out. */\n")
                .append("    public ").append(optional).append('<').append(name).append("> findById(")
                .append(idType).append(" id, ").append(configure)
                .append(") {\n        return operations.findById(id, configured(query));\n    }\n");
        body.append("\n    /** Reads every row, in unspecified order. */\n")
                .append("    public ").append(list).append('<').append(name).append("> findMany() {\n")
                .append("        return operations.findMany(").append(emptyQuery).append(");\n    }\n");
        body.append("\n    /** Reads every row matching the query, with its included relations. */\n")
                .append("    public ").append(list).append('<').append(name).append("> findMany(")
                .append(configure).append(") {\n        return operations.findMany(configured(query));\n    }\n");
        body.append("\n    /** Reads the first row matching the query; order it to make \"first\" well defined. */\n")
                .append("    public ").append(optional).append('<').append(name).append("> findFirst(")
                .append(configure).append(") {\n        return operations.findFirst(configured(query));\n    }\n");
        body.append("\n    /** Reads one page of cursor pagination; the query must set take. */\n")
                .append("    public ").append(refs.use(QUERY + "CursorPage")).append('<').append(name)
                .append("> findManyCursor(").append(configure)
                .append(") {\n        return operations.findManyCursor(configured(query));\n    }\n");
        body.append("\n    /** Opens a forward-only stream; requires a transaction and must be closed. */\n")
                .append("    public ").append(refs.use(RUNTIME + "TuprelStream")).append('<').append(name)
                .append("> stream(").append(configure)
                .append(") {\n        return operations.stream(configured(query));\n    }\n");
        String projection = refs.use(QUERY + "Projection") + "<" + name + ", " + projected + "> projection";
        body.append("\n    /** Reads only the projected columns of every row. */\n")
                .append("    public <").append(projected).append("> ").append(list).append('<').append(projected)
                .append("> select(").append(projection)
                .append(") {\n        return operations.select(projection, ").append(emptyQuery).append(");\n    }\n");
        body.append("\n    /** Reads only the projected columns of every row matching the query. */\n")
                .append("    public <").append(projected).append("> ").append(list).append('<').append(projected)
                .append("> select(").append(projection).append(", ").append(configure)
                .append(") {\n        return operations.select(projection, configured(query));\n    }\n");
        body.append("\n    /** Counts every row. */\n    public long count() {\n        return operations.count(")
                .append(emptyQuery).append(");\n    }\n");
        body.append("\n    /** Counts rows matching the query condition. */\n    public long count(")
                .append(configure).append(") {\n        return operations.count(configured(query));\n    }\n");
        body.append("\n    /** Whether any row matches the query condition. */\n    public boolean exists(")
                .append(configure).append(") {\n        return operations.exists(configured(query));\n    }\n");
        if (version.isPresent()) {
            body.append("\n    /**\n     * Changes the present input fields if the stored version equals {@code expectedVersion},\n")
                    .append("     * increments the version and returns the changed row; empty if no row has the\n")
                    .append("     * identifier. A different stored version throws OptimisticLockException.\n     */\n")
                    .append("    public ").append(optional).append('<').append(name).append("> updateById(")
                    .append(idType).append(" id, long expectedVersion, ").append(name).append("Update input) {\n")
                    .append("        return operations.updateById(id, expectedVersion, values(input));\n    }\n");
        } else {
            body.append("\n    /** Changes the present input fields and returns the changed row, if it exists. */\n")
                    .append("    public ").append(optional).append('<').append(name).append("> updateById(")
                    .append(idType).append(" id, ").append(name).append("Update input) {\n")
                    .append("        return operations.updateById(id, values(input));\n    }\n");
        }
        body.append("\n    /** Changes the present input fields of every row matching the condition; returns the count. */\n")
                .append("    public long updateMany(").append(condition).append(", ").append(name)
                .append("Update input) {\n        return operations.updateMany(where, values(input));\n    }\n");
        body.append("\n    /** Deletes the row with the identifier; returns whether a row was deleted. */\n")
                .append("    public boolean deleteById(").append(idType)
                .append(" id) {\n        return operations.deleteById(id);\n    }\n");
        body.append("\n    /** Deletes every row matching the condition; returns the count. */\n")
                .append("    public long deleteMany(").append(condition)
                .append(") {\n        return operations.deleteMany(where);\n    }\n");
        body.append("\n    /** Renders the statement findMany would execute for the rows, without running it. */\n")
                .append("    public ").append(refs.use("dev.tuprel.sql.RenderedSql")).append(" preview(")
                .append(configure).append(") {\n        return operations.preview(configured(query));\n    }\n");
        for (boolean update : List.of(false, true)) {
            body.append("\n    private static ").append(assignments).append(" values(").append(name)
                    .append(update ? "Update" : "Create").append(" input) {\n        ").append(objects)
                    .append(".requireNonNull(input, \"input\");\n        ").append(assignments).append(" values = ")
                    .append(emptyAssignments).append(";\n");
            for (ValidatedField field : columns) {
                if (update && (field.id() || field.version())) {
                    continue;
                }
                body.append("        if (input.").append(field.name()).append("().present()) {\n")
                        .append("            values = values.set(").append(where).append('.').append(field.name())
                        .append("(), input.").append(field.name()).append("().value());\n        }\n");
            }
            body.append("        return values;\n    }\n");
        }
        body.append("\n    private static ").append(query).append(" configured(").append(configure)
                .append(") {\n        ").append(objects).append(".requireNonNull(query, \"query\");\n")
                .append("        return ").append(objects).append(".requireNonNull(query.apply(")
                .append(emptyQuery).append("), \"query result\");\n    }\n}\n");
        return source(root + ".client", imports, body.toString());
    }

    private static String renderRelationSupport(String root) {
        return source(root, Set.of("java.util.Objects"), """
                /**
                 * State of one relation component: loaded with a value, or not loaded. A relation is
                 * loaded only when a query includes it; reading it otherwise fails with a message that
                 * names the include to add, and never queries the database.
                 */
                public final class TuprelRelation<T> {
                    private final String model;
                    private final String field;
                    private final boolean loaded;
                    private final T value;

                    private TuprelRelation(String model, String field, boolean loaded, T value) {
                        this.model = Objects.requireNonNull(model, "model");
                        this.field = Objects.requireNonNull(field, "field");
                        this.loaded = loaded;
                        this.value = value;
                    }

                    /** A relation that was not requested. */
                    public static <T> TuprelRelation<T> notLoaded(String model, String field) {
                        return new TuprelRelation<>(model, field, false, null);
                    }

                    /** A relation loaded with a value: a list, an optional or a single row. */
                    public static <T> TuprelRelation<T> loaded(String model, String field, T value) {
                        return new TuprelRelation<>(model, field, true, Objects.requireNonNull(value, "value"));
                    }

                    /** Whether the relation was loaded. */
                    public boolean isLoaded() {
                        return loaded;
                    }

                    /** The loaded value; fails if the relation was not included. */
                    public T get() {
                        if (!loaded) {
                            throw new IllegalStateException(model + "." + field + " was not loaded. Add include("
                                    + model + "Include." + field + "()) to the query.");
                        }
                        return value;
                    }

                    @Override public boolean equals(Object other) {
                        return other instanceof TuprelRelation<?> relation && loaded == relation.loaded
                                && model.equals(relation.model) && field.equals(relation.field)
                                && Objects.equals(value, relation.value);
                    }

                    @Override public int hashCode() {
                        return Objects.hash(model, field, loaded, value);
                    }

                    @Override public String toString() {
                        return loaded ? "TuprelRelation[" + value + "]" : "TuprelRelation[not loaded]";
                    }
                }
                """);
    }

    private static String lowerFirst(String name) {
        return Character.toLowerCase(name.charAt(0)) + name.substring(1);
    }

    private static String renderSchema(String root, List<ValidatedModel> models) {
        Set<String> imports = new TreeSet<>();
        imports.add("java.util.List");
        for (ValidatedModel model : models) {
            imports.add(root + ".model." + model.name());
            imports.add(root + ".create." + model.name() + "Create");
            imports.add(root + ".update." + model.name() + "Update");
            imports.add(root + ".fields." + model.name() + "Fields");
        }
        StringBuilder body = new StringBuilder("/** Generated schema descriptors; no database operations. */\n")
                .append("public final class TuprelSchema {\n");
        for (ValidatedModel model : models) {
            body.append("    public static final TuprelModel<").append(model.name()).append(", ")
                    .append(model.name()).append("Create, ").append(model.name()).append("Update> ")
                    .append(model.name().toUpperCase(Locale.ROOT)).append(" = new TuprelModel<>(")
                    .append(quote(model.name())).append(", List.of(");
            for (int index = 0; index < model.fields().size(); index++) {
                if (index > 0) {
                    body.append(", ");
                }
                body.append(model.name()).append("Fields.")
                        .append(model.fields().get(index).name().toUpperCase(Locale.ROOT));
            }
            body.append("));\n");
        }
        body.append("\n    private TuprelSchema() {}\n}\n");
        return source(root, imports, body.toString());
    }

    private static String renderInputSupport(String root) {
        return source(root, Set.of(), """
                /** Presence and value are independent: an optional field may be present with null. */
                public record TuprelInput<T>(boolean present, T value) {
                    public TuprelInput {
                        if (!present && value != null) {
                            throw new IllegalArgumentException("Absent input cannot carry a value");
                        }
                    }

                    public static <T> TuprelInput<T> absent() {
                        return new TuprelInput<>(false, null);
                    }

                    public static <T> TuprelInput<T> of(T value) {
                        return new TuprelInput<>(true, value);
                    }
                }
                """);
    }

    private static String renderFieldSupport(String root) {
        return source(root, Set.of("java.util.Objects"), """
                /** Declarative field metadata; it does not execute a query. */
                public record TuprelField<T>(String name, String schemaType, Cardinality cardinality,
                        String relationTarget) {
                    public TuprelField {
                        Objects.requireNonNull(name, "name");
                        Objects.requireNonNull(schemaType, "schemaType");
                        Objects.requireNonNull(cardinality, "cardinality");
                    }

                    public enum Cardinality { REQUIRED, OPTIONAL, LIST }
                }
                """);
    }

    private static String renderModelSupport(String root) {
        return source(root, Set.of("java.util.List", "java.util.Objects"), """
                /** Typed model descriptor; database operations are deferred. */
                public record TuprelModel<M, C, U>(String name, List<TuprelField<?>> fields) {
                    public TuprelModel {
                        Objects.requireNonNull(name, "name");
                        fields = List.copyOf(fields);
                    }
                }
                """);
    }

    private static String renderBytes(String root) {
        return source(root, Set.of("java.util.Arrays", "java.util.Objects"), """
                /** Immutable byte value with content equality. */
                public final class TuprelBytes {
                    private final byte[] value;

                    public TuprelBytes(byte[] value) {
                        this.value = Objects.requireNonNull(value, "value").clone();
                    }

                    public byte[] value() {
                        return value.clone();
                    }

                    @Override public boolean equals(Object other) {
                        return other instanceof TuprelBytes bytes && Arrays.equals(value, bytes.value);
                    }

                    @Override public int hashCode() {
                        return Arrays.hashCode(value);
                    }

                    @Override public String toString() {
                        return "TuprelBytes[" + value.length + " bytes]";
                    }
                }
                """);
    }

    private static String renderJson(String root) {
        return source(root, Set.of("java.util.Objects"), """
                /** Immutable raw JSON text; parsing and database binding are deferred. */
                public record TuprelJson(String text) {
                    public TuprelJson {
                        Objects.requireNonNull(text, "text");
                    }
                }
                """);
    }
}
